site_name: AI Challenge 2024
site_url: https://automotiveaichallenge.github.io/aichallenge-documentation-2024/
repo_url: https://github.com/AutomotiveAIChallenge/aichallenge-documentation-2024
docs_dir: docs
copyright: "&copy; 2024 TIER IV, Inc."
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    scheme: slate
    primary: custom
    accent: red
    # logo:
    # favicon:

nav:
  - index: index.md
  - getting-started.md
  - information:
      - information/schedule.md
      - information/rules.md
  - submission.md
  - setup:
      - setup/requirements.md
      - setup/workspace-setup.md
      - setup/docker.md
      - setup/headless-simulation.md
      - setup/visible-simulation.md
  - development:
      - development/workspace-usage.md
      - development/main-module.md
  - specifications:
      - specifications/interface.md
      - specifications/hardware.md
      - specifications/simulator.md
  - course:
      - course/index.md
      - course/vehicle.md
      - course/velocity_planning.md
      - course/perception.md
  - FAQ: faq.md
  - Community: community.md

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true
          nav_translations:
            index: トップページ
            information: 大会情報
            setup: 導入
            development: 開発
            specifications: 仕様
            course: 講座
        - locale: en
          name: English
          build: true
          nav_translations:
            index: Top Page
            information: Information
            setup: Setup
            development: Development
            specifications: Specifications
            course: Course
