site_name: AI Challenge 2024
site_url: https://automotiveaichallenge.github.io/aichallenge-documentation-2024/
repo_url: https://github.com/AutomotiveAIChallenge/aichallenge-documentation-2024
docs_dir: docs
copyright: "&copy; 2024 TIER IV, Inc."
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    scheme: slate
    primary: custom
    accent: red
    # logo:
    # favicon:

nav:
  - index: index.md
  - getting-started.md
  - information.md
  - competition:
      - competition/rules.md
      - competition/preliminaries.md
      - competition/finals.md
  - course:
      - course/index.md
      - course/vehicle.md
      - course/velocity_planning.md
      - course/perception.md
  - specifications:
      - specifications/interface.md
      - specifications/hardware.md
      - specifications/simulator.md
  - development:
      - development/installation.md
      - development/workspace.md
      - development/visible-simulation.md
      - development/main-module.md
      - development/device-drivers.md
      - development/requirements.md
  - FAQ: faq.md
  - Community: community.md

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true
          nav_translations:
            index: トップページ
            competition: 競技内容
            course: 講座
            development: 開発
            specifications: 仕様
        - locale: en
          name: English
          build: true
          nav_translations:
            index: Top Page
            competition: Competition
            course: Course
            development: Development
            specifications: Specifications
